check result file

diff --git a/ntp_shps b/ntp_shps
--- a/ntp_shps
+++ b/ntp_shps
@@ -338,6 +338,12 @@ if test $DTYPE == o -o $DTYPE == d -o $DTYPE == j -o $DTYPE == r
       }' > $LIST
 fi
 
+if test ! -s $LIST
+  then
+    echo "$0: error - file $LIST not generated - program terminated " 1>&2
+    exit 1
+fi
+
 if test -n "$AVGLINE"
   then
     AVG="\n average: `grep -v '^#' $LIST | head -1 | $AWK '{ print $3 }'`"
